---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: test-net
  labels:
  annotations:
spec:
  config:  '{ "cniVersion": "0.3.1", "type": "macvlan", "master": "enp1s0", "mode": "bridge", "ipam": { "type": "whereabouts", "range": "192.168.25.0/24" } }'
