---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus-hostnet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: multus-hostnetRole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multus-hostnetRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: multus-hostnetRole
subjects:
  - kind: ServiceAccount
    name: multus-hostnet
