apiVersion: batch/v1
kind: Job
metadata:
  name: "setup-job-{{ .NodeName }}"
  namespace: {{ .Namespace }}
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "setup-job-{{ .NodeName }}"
      namespace: {{ .Namespace }}
    spec:
      containers:
      - name: setup-job
        image: quay.io/rcampos/multus-hostnet:latest
        command:
          - /bin/setup-job
        securityContext:
          privileged: true
          capabilities:
            add:
              # Needed for ip and link configuration
              - NET_ADMIN
              # Needed for network namespace operations
              - SYS_ADMIN
        volumeMounts:
          - name: netns
            mountPath: /var/run/netns
      nodeName: "{{ .NodeName }}"
      hostNetwork: true
      volumes:
        - name: netns
          hostPath:
            path: /var/run/netns
      restartPolicy: Never
